# Generated by Django 4.2 on 2023-05-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('tmp', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
