# Generated by Django 4.2 on 2023-05-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=13, unique=True, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
